import type { Locale } from "@/stores/ui.store";

const zhCN = {
  "common.cancel": "取消", "common.confirm": "确认", "common.create": "创建", "common.creating": "创建中…", "common.delete": "删除", "common.deleting": "删除中…", "common.deleteConfirm": "确定删除“{name}”吗？", "common.folderDeleteWarning": "目录中的所有笔记都会被永久删除。", "common.noteDeleteWarning": "此操作不可恢复。", "common.loading": "加载中…", "common.move": "移动", "common.moving": "移动中…", "common.remove": "移除", "common.retry": "重试", "common.save": "保存", "common.saving": "保存中…",
  "auth.connect": "连接 GitHub", "auth.description": "粘贴一个可写仓库的 Personal Access Token，会保存在本地加密文件中，绝不落盘明文。", "auth.validated": "校验通过：{login}", "auth.getToken": "如何获取 Token", "auth.continue": "确认并继续", "auth.validating": "校验中…", "auth.validate": "校验 Token",
  "repo.setup": "设置笔记仓库", "repo.bindExisting": "绑定已有", "repo.create": "新建仓库", "repo.bindTitle": "绑定已有仓库", "repo.bindDescription": "输入 GitHub 仓库 HTTPS 地址，AINote 会克隆到本地并建立连接。", "repo.binding": "绑定中…", "repo.bind": "绑定", "repo.createTitle": "新建笔记仓库", "repo.createDescription": "在 GitHub 上创建仓库并自动绑定，笔记会以 Markdown 文件存入其中。", "repo.namePlaceholder": "仓库名（如 my-notes）", "repo.private": "私有仓库（推荐）", "repo.createAndBind": "创建并绑定", "repo.add": "添加仓库", "repo.current": "当前", "repo.setCurrent": "设为当前：{name}", "repo.rename": "重命名：{name}", "repo.remove": "移除：{name}", "repo.none": "还没有笔记仓库，点击右上角添加。", "repo.removeTitle": "移除仓库", "repo.removeConfirm": "确定移除「{name}」？仅取消绑定，本地笔记数据不会被删除。", "repo.removing": "移除中…", "repo.renameTitle": "重命名仓库", "repo.name": "仓库名称",
  "settings.title": "设置", "settings.account": "账户", "settings.logout": "退出登录", "settings.loggingOut": "退出中…", "settings.appearance": "外观", "settings.theme": "主题", "settings.light": "亮色", "settings.dark": "暗色", "settings.language": "语言", "settings.chinese": "简体中文", "settings.english": "English",
  "tree.label": "目录", "tree.navigation": "笔记目录树", "tree.newNote": "新建笔记", "tree.newFolder": "新建文件夹", "tree.newHere": "在此目录新建笔记", "tree.newFolderHere": "在此目录新建文件夹", "tree.deleteFailed": "删除失败：{message}", "tree.newChildFolder": "新建子目录", "tree.collapse": "收起目录", "tree.expand": "展开目录", "tree.deleteFolder": "删除目录", "tree.openNote": "打开笔记", "tree.renameMove": "移动 / 重命名", "tree.deleteNote": "删除笔记", "tree.copyPath": "复制路径", "tree.pathCopied": "已复制路径", "tree.folderPath": "如：daily/2026（自动建父目录）", "tree.folderExists": "目录已存在，创建将保留现有目录", "tree.folderPathRequired": "请输入文件夹路径", "tree.folderExtension": "文件夹名不应以 .md 结尾",
  "note.newTitle": "新建笔记", "note.pathPlaceholder": "如：daily/我的笔记（自动补 .md）", "note.exists": "已存在同名笔记，创建将打开已有文件", "note.template": "模板", "note.defaultTemplate": "默认（# 未命名）", "note.dailyTemplate": "每日（日期标题）", "note.blankTemplate": "空白", "note.pathRequired": "请输入笔记路径", "note.moveTitle": "重命名 / 移动", "note.current": "当前：{path}", "note.targetPath": "目标路径，如 daily/新名字.md", "note.targetRequired": "请输入目标路径", "note.empty": "选择或新建一篇笔记开始写作", "note.loadFailed": "加载失败：{message}", "note.edit": "编辑", "note.split": "分栏", "note.preview": "预览", "note.saved": "已保存", "note.unsaved": "有未保存修改", "note.moving": "移动 / 重命名", "note.headingLevel": "标题级别", "note.body": "正文", "note.bold": "加粗", "note.italic": "斜体", "note.strikethrough": "删除线", "note.inlineCode": "行内代码", "note.quote": "引用", "note.bulletList": "无序列表", "note.orderedList": "有序列表", "note.taskList": "任务列表", "note.image": "图片", "note.codeBlock": "代码块", "note.table": "表格", "note.divider": "分割线", "note.link": "链接", "note.all": "全部笔记", "note.recentSort": "按最近编辑排序", "note.none": "还没有笔记", "note.noneDescription": "创建第一篇笔记，开始整理你的想法", "note.listDeleteConfirm": "删除笔记「{name}」？此操作不可恢复。", "note.resize": "调整编辑/预览比例",
  "sync.conflict": "存在冲突", "sync.now": "立即同步", "sync.starting": "初始化同步中…", "sync.syncing": "同步中…", "sync.resolving": "处理中…", "sync.offlinePending": "离线待同步", "sync.offline": "离线", "sync.pushPull": "待推送且可拉取", "sync.push": "待推送 {count} 个提交", "sync.pull": "可拉取 {count} 个提交", "sync.unsaved": "有待保存变更", "sync.synced": "已同步", "sync.resolveConflict": "解决同步冲突", "sync.localLibrary": "本地知识库", "sync.noLibrary": "尚未绑定知识库", "sync.offlineEdit": " · 离线可继续编辑", "sync.checkpoint": "保存版本", "sync.checkpointHint": "将当前编辑保存为一个版本", "sync.conflictTitle": "同步发生冲突", "sync.conflictDescription": "本地与远端对同一内容都有修改，请选择保留哪一侧。图形化合并将在后续版本提供。", "sync.later": "稍后处理", "sync.remote": "使用远端", "sync.keepLocal": "保留本地",
  "update.title": "软件更新", "update.description": "从 GitHub Releases 获取签名更新", "update.install": "更新到 {version}", "update.installing": "安装中…", "update.check": "检查更新", "update.checking": "检查中…", "update.found": "发现新版本 {version}{details}", "update.latest": "当前已是最新版本。", "update.checkFailed": "检查更新失败", "update.installFailed": "安装更新失败",
  "app.authLoadFailed": "加载认证状态失败", "app.workspaceNavigation": "工作区导航", "app.notes": "笔记", "app.recent": "最近", "app.favorites": "收藏", "app.noteContent": "笔记内容",
} as const;

const enUS: Record<keyof typeof zhCN, string> = {
  "common.cancel": "Cancel", "common.confirm": "Confirm", "common.create": "Create", "common.creating": "Creating…", "common.delete": "Delete", "common.deleting": "Deleting…", "common.deleteConfirm": "Delete “{name}”?", "common.folderDeleteWarning": "All notes in this folder will be permanently deleted.", "common.noteDeleteWarning": "This action cannot be undone.", "common.loading": "Loading…", "common.move": "Move", "common.moving": "Moving…", "common.remove": "Remove", "common.retry": "Retry", "common.save": "Save", "common.saving": "Saving…",
  "auth.connect": "Connect GitHub", "auth.description": "Paste a Personal Access Token with repository write access. It is stored locally in encrypted storage and never written to disk in plain text.", "auth.validated": "Verified: {login}", "auth.getToken": "How to get a token", "auth.continue": "Confirm and continue", "auth.validating": "Verifying…", "auth.validate": "Verify token",
  "repo.setup": "Set up your notes repository", "repo.bindExisting": "Bind existing", "repo.create": "Create repository", "repo.bindTitle": "Bind an existing repository", "repo.bindDescription": "Enter a GitHub repository HTTPS URL. AINote will clone it locally and connect it.", "repo.binding": "Binding…", "repo.bind": "Bind", "repo.createTitle": "Create a notes repository", "repo.createDescription": "Create and bind a GitHub repository. Your notes are stored there as Markdown files.", "repo.namePlaceholder": "Repository name (e.g. my-notes)", "repo.private": "Private repository (recommended)", "repo.createAndBind": "Create and bind", "repo.add": "Add repository", "repo.current": "Current", "repo.setCurrent": "Set current: {name}", "repo.rename": "Rename: {name}", "repo.remove": "Remove: {name}", "repo.none": "No notes repositories yet. Use Add repository above.", "repo.removeTitle": "Remove repository", "repo.removeConfirm": "Remove “{name}”? This only unbinds it; your local notes will not be deleted.", "repo.removing": "Removing…", "repo.renameTitle": "Rename repository", "repo.name": "Repository name",
  "settings.title": "Settings", "settings.account": "Account", "settings.logout": "Log out", "settings.loggingOut": "Logging out…", "settings.appearance": "Appearance", "settings.theme": "Theme", "settings.light": "Light", "settings.dark": "Dark", "settings.language": "Language", "settings.chinese": "简体中文", "settings.english": "English",
  "tree.label": "Files", "tree.navigation": "Notes file tree", "tree.newNote": "New note", "tree.newFolder": "New folder", "tree.newHere": "New note here", "tree.newFolderHere": "New folder here", "tree.deleteFailed": "Delete failed: {message}", "tree.newChildFolder": "New subfolder", "tree.collapse": "Collapse folder", "tree.expand": "Expand folder", "tree.deleteFolder": "Delete folder", "tree.openNote": "Open note", "tree.renameMove": "Move / rename", "tree.deleteNote": "Delete note", "tree.copyPath": "Copy path", "tree.pathCopied": "Path copied", "tree.folderPath": "e.g. daily/2026 (parent folders are created automatically)", "tree.folderExists": "The folder already exists and will be retained.", "tree.folderPathRequired": "Enter a folder path", "tree.folderExtension": "A folder name cannot end in .md",
  "note.newTitle": "New note", "note.pathPlaceholder": "e.g. daily/my-note (.md is added automatically)", "note.exists": "A note with this name already exists; it will be opened instead.", "note.template": "Template", "note.defaultTemplate": "Default (# Untitled)", "note.dailyTemplate": "Daily (date heading)", "note.blankTemplate": "Blank", "note.pathRequired": "Enter a note path", "note.moveTitle": "Move / rename", "note.current": "Current: {path}", "note.targetPath": "Target path, e.g. daily/new-name.md", "note.targetRequired": "Enter a target path", "note.empty": "Select or create a note to start writing", "note.loadFailed": "Could not load note: {message}", "note.edit": "Edit", "note.split": "Split", "note.preview": "Preview", "note.saved": "Saved", "note.unsaved": "Unsaved changes", "note.moving": "Move / rename", "note.headingLevel": "Heading level", "note.body": "Body", "note.bold": "Bold", "note.italic": "Italic", "note.strikethrough": "Strikethrough", "note.inlineCode": "Inline code", "note.quote": "Quote", "note.bulletList": "Bulleted list", "note.orderedList": "Numbered list", "note.taskList": "Task list", "note.image": "Image", "note.codeBlock": "Code block", "note.table": "Table", "note.divider": "Divider", "note.link": "Link", "note.all": "All notes", "note.recentSort": "Sorted by last edited", "note.none": "No notes yet", "note.noneDescription": "Create your first note and start organizing your thoughts", "note.listDeleteConfirm": "Delete note “{name}”? This action cannot be undone.", "note.resize": "Resize editor and preview",
  "sync.conflict": "Conflict detected", "sync.now": "Sync now", "sync.starting": "Starting sync…", "sync.syncing": "Syncing…", "sync.resolving": "Resolving…", "sync.offlinePending": "Offline, sync pending", "sync.offline": "Offline", "sync.pushPull": "Changes to push and pull", "sync.push": "{count} commits to push", "sync.pull": "{count} commits to pull", "sync.unsaved": "Unsaved changes", "sync.synced": "Synced", "sync.resolveConflict": "Resolve sync conflict", "sync.localLibrary": "Local knowledge base", "sync.noLibrary": "No knowledge base bound", "sync.offlineEdit": " · You can continue editing offline", "sync.checkpoint": "Save version", "sync.checkpointHint": "Save current edits as a version", "sync.conflictTitle": "Sync conflict", "sync.conflictDescription": "The same content was changed locally and remotely. Choose which version to keep. A visual merge tool will arrive in a later release.", "sync.later": "Handle later", "sync.remote": "Use remote", "sync.keepLocal": "Keep local",
  "update.title": "Software updates", "update.description": "Get signed updates from GitHub Releases", "update.install": "Update to {version}", "update.installing": "Installing…", "update.check": "Check for updates", "update.checking": "Checking…", "update.found": "New version {version}{details}", "update.latest": "You’re up to date.", "update.checkFailed": "Could not check for updates", "update.installFailed": "Could not install update",
  "app.authLoadFailed": "Could not load authentication status", "app.workspaceNavigation": "Workspace navigation", "app.notes": "Notes", "app.recent": "Recent", "app.favorites": "Favorites", "app.noteContent": "Note content",
};

export type TranslationKey = keyof typeof zhCN;
export const messages: Record<Locale, Record<TranslationKey, string>> = { "zh-CN": zhCN, "en-US": enUS };
